blueprint:
  name: "Room Music Follow - YT Music"
  description: "**Version: 1.1**\n\nMake YT Music Follow You Around Your Home"
  author: fixtse
  domain: script
  input:
    yt_music_player:
      name: YT Music Player
      description: Youtube Music Media Player
      selector:
        entity:
          domain: media_player
    media_player:
      name: Media Player
      description: Media Player to Play the music
      selector:
        entity:
          domain: media_player
    media_play:
      name: Media to Play
      description: Select Any song or playlist to be played if nothing is currently playing 
      selector:
        media:  
    shuffle:
      name: Shuffle
      default: disable_shuffle
      selector:
        select:
          options:
          - label: Enable
            value: enable_shuffle
          - label: Disable
            value: disable_shuffle
          multiple: false
          custom_value: false
          sort: false
  source_url: https://github.com/fixtse/blueprints/blob/main/follow_yt_music.yaml
variables:
  media_player:  !input media_player
  shuffle: !input shuffle
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input yt_music_player
            state: playing
        sequence:
          - service: media_player.select_source
            data:
              source: "{{ media_player }}"
            entity_id: !input yt_music_player
    default:
      - service: media_player.select_source
        data:
          source: "{{ media_player }}"
          entity_id: !input yt_music_player
      - if:
        - condition: template
          value_template: '{{ ''enable_shuffle''
                    in shuffle }}'
        then:
        - service: media_player.shuffle_set
          data:
            shuffle: true
          target:
            entity_id: !input yt_music_player
        else:
        - service: media_player.shuffle_set
          data:
            shuffle: false
          target:
            entity_id: !input yt_music_player
      - service: media_player.play_media
        data: !input media_play
mode: queued
