blueprint:
  name: Room Music Follow - Spotify
  description: "**Version: 2.0**\n\n Make Spotify Follow You Around Your Home \n\n Recent Changes:\n - Added support for Spotcast v6 alpha"
  author: fixtse
  domain: script
  input:
    spotify_player:
      name: Spotify Player
      description: Spotify Media Player
      selector:
        entity:
          domain:
            - media_player
          integration: spotify
          multiple: false
    media_player:
      name: Media Player
      description: Media Player to Play the music
      selector:
        entity:
          domain:
            - media_player
          multiple: false
    shuffle:
      name: Shuffle
      default: []
      selector:
        select:
          options:
            - label: Enable
              value: enable_shuffle
          multiple: true
          custom_value: false
          sort: false
    repeat:
      name: Repeat Mode
      default: "context"
      selector:
        select:
          options:
            - label: Context (Default)
              value: context
            - label: Track
              value: track
            - label: "Off"
              value: "off"
          multiple: false
          custom_value: false
          sort: false
    uri:
      name: URI
      description: The URI of the playlist to play
      selector:
        text: {}
    not_default:
      name: Multiple Account Support
      icon: mdi:account-multiple-plus-outline
      collapsed: false
      input:
        activate_feature_multi_account:
          name: Use specific account
          description: "Leave disabled to use default account"
          default: []
          selector:
            select:
              options:
                - label: Use specific account
                  value: use_specific_account
              multiple: true
              custom_value: false
              sort: false
        account_name:
          name: Integration
          description: Select the Account's Integration
          default: []
          selector:
            config_entry:
              integration: spotcast
  source_url: https://github.com/fixtse/blueprints/blob/main/follow_spotify.yaml
variables:
  media_player: !input media_player
  uri: !input uri
  shuffle: !input shuffle
  repeat: !input repeat
  activate_feature_multi_account: !input activate_feature_multi_account
  account_name: !input account_name
  shuffle_enabled: "{{ 'enable_shuffle' in shuffle }}"
sequence:
  - if:
      - condition: template
        value_template:
          "{{ 'use_specific_account' in activate_feature_multi_account
          }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input spotify_player
                state: playing
            sequence:
              - service: spotcast.transfer_playback
                data:
                  media_player:
                    entity_id: "{{ media_player }}"
                  account: "{{ account_name }}"
        default:
          - service: spotcast.play_media
            data:
              spotify_uri: "{{ uri }}"
              media_player:
                entity_id: "{{ media_player }}"
              account: "{{ account_name }}"
              data:
                shuffle: "{{ shuffle_enabled }}"
                repeat: "{{ repeat }}"
    else:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input spotify_player
                state: playing
            sequence:
              - service: spotcast.transfer_playback
                data:
                  media_player:
                    entity_id: "{{ media_player }}"
        default:
          - service: spotcast.play_media
            data:
              spotify_uri: "{{ uri }}"
              media_player:
                entity_id: "{{ media_player }}"
              data:
                shuffle: "{{ shuffle_enabled }}"
                repeat: "{{ repeat }}"
mode: queued